In [1]:
# google drive 마운트
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
import pandas as pd
import numpy as np
  
part1 = pd.read_csv('/content/drive/MyDrive/국민대학원/졸업프로젝트/데이터/1차 병합본/지리/제주특별자치도_도지정문화재현황.csv', encoding='cp949')
part2 = pd.read_csv('/content/drive/MyDrive/국민대학원/졸업프로젝트/데이터/1차 병합본/지리/제주특별자치도_오름현황.csv', encoding='cp949')

In [3]:
# part1 = 제주특별자치도_도지정문화재현황

print(part1.shape)
print(list(part1.columns))
part1.head()

(260, 6)
['Unnamed: 0', '이름', '행정시', '도로명주소', '위도', '경도']

   Unnamed: 0    이름  행정시                       도로명주소  위도  경도
0           0  제주향교  NaN          제주특별자치도 제주시 서문로 47 NaN NaN
1           1   연북정  NaN    제주특별자치도 제주시 조천읍 조천리 2690 NaN NaN
2           2  대정향교  NaN   제주특별자치도 서귀포시 안덕면 사계리 3126 NaN NaN
3           3  정의향교  NaN  제주특별자치도 서귀포시 표선면 성읍리 820-1 NaN NaN
4           4   향사당  NaN      제주특별자치도 제주시 삼도1동 970-2 NaN NaN

In [4]:
# part2 = 제주특별자치도_오름현황

print(part2.shape)
print(list(part2.columns))
part2.head()

(368, 6)
['Unnamed: 0', '이름', '행정시', '도로명주소', '위도', '경도']

   Unnamed: 0     이름   행정시                        도로명주소  위도  경도
0           0   가마오름   제주시     제주특별자치도 제주시 한경면 청수리 1202 NaN NaN
1           1   가메오름   제주시     제주특별자치도 제주시 애월읍 봉성리 산124 NaN NaN
2           2    가메옥   제주시     제주특별자치도 제주시 구좌읍 송당리 1712 NaN NaN
3           3    가메창   제주시     제주특별자치도 제주시 한경면 저지리 1496 NaN NaN
4           4  가문이오름  서귀포시  제주특별자치도 서귀포시 표선면 가시리 산158-2 NaN NaN

In [5]:
new_part = pd.concat([part1, part2])

print(new_part.shape)
print(list(new_part.columns))
new_part.head()

(628, 6)
['Unnamed: 0', '이름', '행정시', '도로명주소', '위도', '경도']

   Unnamed: 0    이름  행정시                       도로명주소  위도  경도
0           0  제주향교  NaN          제주특별자치도 제주시 서문로 47 NaN NaN
1           1   연북정  NaN    제주특별자치도 제주시 조천읍 조천리 2690 NaN NaN
2           2  대정향교  NaN   제주특별자치도 서귀포시 안덕면 사계리 3126 NaN NaN
3           3  정의향교  NaN  제주특별자치도 서귀포시 표선면 성읍리 820-1 NaN NaN
4           4   향사당  NaN      제주특별자치도 제주시 삼도1동 970-2 NaN NaN

In [6]:
# 'Unnamed: 0' 컬럼 삭제

new_part = new_part.drop(['Unnamed: 0'], axis=1)
new_part.head()

     이름  행정시                       도로명주소  위도  경도
0  제주향교  NaN          제주특별자치도 제주시 서문로 47 NaN NaN
1   연북정  NaN    제주특별자치도 제주시 조천읍 조천리 2690 NaN NaN
2  대정향교  NaN   제주특별자치도 서귀포시 안덕면 사계리 3126 NaN NaN
3  정의향교  NaN  제주특별자치도 서귀포시 표선면 성읍리 820-1 NaN NaN
4   향사당  NaN      제주특별자치도 제주시 삼도1동 970-2 NaN NaN

In [7]:
# csv 파일 저장

new_part.to_csv('제주특별자치도_지리_병합.csv', encoding='cp949')