In [1]:
# google drive 마운트
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
import pandas as pd
import numpy as np
  
part1 = pd.read_csv('/content/drive/MyDrive/국민대학원/졸업프로젝트/데이터/1순위/숙박/제주특별자치도_관광숙박업현황_20210630.csv', encoding='cp949')
part2 = pd.read_csv('/content/drive/MyDrive/국민대학원/졸업프로젝트/데이터/1순위/숙박/제주특별자치도 제주시_관광숙박업현황_20210228.csv', encoding='cp949')

# part2 = 제주특별자치도_제주시_관광숙박업현황

In [3]:
# part2 = 제주특별자치도 제주시_관광숙박업현황

print(part2.shape)
print(list(part2.columns))
part2.head()

(207, 7)
['구분', '상호명', '소재지', '객실수', '연락처', '비고', '데이터기준일자']

,구분,상호명,소재지,객실수,연락처,비고,데이터기준일자
0,관광호텔업,글래드호텔앤리조트(주)메종글래드제주,제주특별자치도 제주시 노연로 80,513,064-747-5000,특이사항없음,2021-02-28
1,관광호텔업,제주오리엔탈호텔,제주특별자치도 제주시 탑동로 47,321,064-752-8222,특이사항없음,2021-02-28
2,관광호텔업,제주KAL호텔,제주특별자치도 제주시 중앙로 151,282,064-724-2001,특이사항없음,2021-02-28
3,관광호텔업,제주썬호텔,제주특별자치도 제주시 삼무로 67,203,064-741-8000,휴업,2021-02-28
4,관광호텔업,제주퍼시픽호텔,제주특별자치도 제주시 서사로 20,177,064-758-2500,특이사항없음,2021-02-28

In [4]:
# 컬럼명 변경

part2.rename(columns = {'소재지':'도로명주소', '연락처':'전화번호'},inplace=True)
part2.head()

,구분,상호명,도로명주소,객실수,전화번호,비고,데이터기준일자
0,관광호텔업,글래드호텔앤리조트(주)메종글래드제주,제주특별자치도 제주시 노연로 80,513,064-747-5000,특이사항없음,2021-02-28
1,관광호텔업,제주오리엔탈호텔,제주특별자치도 제주시 탑동로 47,321,064-752-8222,특이사항없음,2021-02-28
2,관광호텔업,제주KAL호텔,제주특별자치도 제주시 중앙로 151,282,064-724-2001,특이사항없음,2021-02-28
3,관광호텔업,제주썬호텔,제주특별자치도 제주시 삼무로 67,203,064-741-8000,휴업,2021-02-28
4,관광호텔업,제주퍼시픽호텔,제주특별자치도 제주시 서사로 20,177,064-758-2500,특이사항없음,2021-02-28

In [5]:
# '데이터기준일자'. '비고' 제거

part2 = part2.drop(['데이터기준일자', '비고'], axis=1)
part2.head()

      구분                  상호명                  도로명주소  객실수          전화번호
0  관광호텔업  글래드호텔앤리조트(주)메종글래드제주    제주특별자치도 제주시 노연로 80   513  064-747-5000
1  관광호텔업             제주오리엔탈호텔     제주특별자치도 제주시 탑동로 47  321  064-752-8222
2  관광호텔업              제주KAL호텔  제주특별자치도 제주시 중앙로 151    282  064-724-2001
3  관광호텔업                제주썬호텔   제주특별자치도 제주시 삼무로 67    203  064-741-8000
4  관광호텔업              제주퍼시픽호텔   제주특별자치도 제주시 서사로 20    177  064-758-2500

In [6]:
# 누락 데이터 확인

part2.count()

구분       207
상호명      207
도로명주소    207
객실수      207
전화번호     206
dtype: int64

In [7]:
# 완전히 동일한 중복데이터 여부 확인

part2.duplicated().sum()

0

In [8]:
# 컬럼별로 중복데이터 여부 확인

part2['상호명'].value_counts()

(주)블랙스톤리조트             2
글래드호텔앤리조트(주)메종글래드제주    1
호스텔 오렌지트리              1
제이투(J2)                1
레드월 호스텔                1
                      ..
어반아일랜드호텔               1
더스테이센추리호텔              1
오드리 인                  1
스위트캐슬                  1
캠퍼트리호텔앤리조트             1
Name: 상호명, Length: 206, dtype: int64

In [9]:
# 중복 발생

part2[part2.상호명 == '(주)블랙스톤리조트']

           구분         상호명                        도로명주소  객실수          전화번호
19      관광호텔업  (주)블랙스톤리조트  제주특별자치도 제주시 한림읍 한창로 925-122   36  064-795-2126
195  휴양콘도미니엄업  (주)블랙스톤리조트  제주특별자치도 제주시 한림읍 한창로 925-122   50  064-795-2126

In [10]:
# 중복 발생
# 한 상호명에 여러 업을 운영할 수도 있다고 판단해서 중복 삭제 안함

part1[part1.상호명 == '(주)블랙스톤리조트']

,구분,상호명,소재지,객실수,연락처,데이터기준일자
19,관광호텔업,(주)블랙스톤리조트,제주특별자치도 제주시 한림읍 한창로 925-122,36,064-795-2126,2021-06-30
379,휴양콘도미니엄업,(주)블랙스톤리조트,제주특별자치도 제주시 한림읍 한창로 925-122,50,064-795-2126,2021-06-30

In [11]:
# 컬럼별로 중복데이터 여부 확인

part2['도로명주소'].value_counts()

제주특별자치도 제주시 한림읍 금능남로 127       2
제주특별자치도 제주시 한림읍 한창로 925-122    2
제주특별자치도 제주시 조천읍 북선로 125        2
제주특별자치도 제주시 애월읍 신상로 258        1
제주특별자치도 제주시 관덕로8길 7-12         1
                              ..
제주특별자치도 제주시 삼무로 76             1
제주특별자치도 제주시 애월읍 일주서로 7113      1
제주특별자치도 제주시 서해안로 100           1
제주특별자치도 제주시 조천읍 신북로 443        1
제주특별자치도 제주시 해안마을서4길 100        1
Name: 도로명주소, Length: 204, dtype: int64

In [12]:
# 중복 발생
# 한 도로명주소에 여러 업소가 있을 수 있다고 판단해서 중복 삭제 안함

part2[part2.도로명주소 == '제주특별자치도 제주시 한림읍 금능남로 127']

           구분       상호명                     도로명주소  객실수          전화번호
26      관광호텔업    호텔라온제주  제주특별자치도 제주시 한림읍 금능남로 127   51  064-795-8000
203  휴양콘도미니엄업  라온프라이빗타운  제주특별자치도 제주시 한림읍 금능남로 127  934  064-795-3001

In [13]:
# 컬럼별로 중복데이터 여부 확인

part2['전화번호'].value_counts()

064-799-3544    3
064-799-2600    2
064-799-1671    2
064-784-4811    2
064-796-8400    2
               ..
064-711-0008    1
064-740-1900    1
064-800-4000    1
064-710-8000    1
064-795-8888    1
Name: 전화번호, Length: 197, dtype: int64

In [14]:
# 중복 발생
# 여러 업소의 소재지가 매우 유사해서 동일한 전화번호로 운영하고 있을 수 있다고 판단해서 중복 삭제 안함

part2[part2.전화번호 == '064-799-3544']

        구분        상호명                         도로명주소  객실수          전화번호
54   관광호텔업  애월바다호텔 제주  제주특별자치도 제주시 애월읍 애월해안로 554-10   94  064-799-3544
60   관광호텔업   베니키아호텔제주   제주특별자치도 제주시 애월읍 애월해안로 554-6   88  064-799-3544
123   호스텔업   씨클리프호텔제주   제주특별자치도 제주시 애월읍 애월해안로 554-8   41  064-799-3544

In [15]:
# 중복 발생
# 여러 업소의 소재지가 매우 유사해서 동일한 전화번호로 운영하고 있을 수 있다고 판단해서 중복 삭제 안함

part2[part2.전화번호 == '064-796-8400']

           구분        상호명                     도로명주소  객실수          전화번호
180  휴양콘도미니엄업  일성제주콘도미니엄  제주특별자치도 제주시 한림읍 한림로 239    50  064-796-8400
196  휴양콘도미니엄업  일성비치콘도미니엄   제주특별자치도 제주시 한림읍 한림로 127  178  064-796-8400

In [16]:
# 중복 발생
# 여러 업소의 소재지가 매우 유사해서 동일한 전화번호로 운영하고 있을 수 있다고 판단해서 중복 삭제 안함

part2[part2.전화번호 == '064-799-1671']

       구분       상호명                  도로명주소  객실수          전화번호
45  관광호텔업     루스톤호텔  제주특별자치도 제주시 애월해안로 408   42  064-799-1671
46  관광호텔업  루스톤빌라앤호텔  제주특별자치도 제주시 애월해안로 406   38  064-799-1671

In [17]:
# 연락처 결측값 찾기

part2.loc[part2['전화번호'].isna()]

       구분    상호명                       도로명주소  객실수 전화번호
179  호스텔업  마음스테이  제주특별자치도 제주시 구좌읍 평대13길 42-1   20  NaN

# part1 = 제주특별자치도_관광숙박업현황

In [18]:
# part1 = 제주특별자치도_관광숙박업현황

print(part1.shape)
print(list(part1.columns))
part1.head()

(424, 6)
['구분', '상호명', '소재지', '객실수', '연락처', '데이터기준일자']

,구분,상호명,소재지,객실수,연락처,데이터기준일자
0,관광호텔업,글래드호텔앤리조트(주)메종글래드제주,제주특별자치도 제주시 노연로 80,513,064-747-5000,2021-06-30
1,관광호텔업,제주오리엔탈호텔,제주특별자치도 제주시 탑동로 47,321,064-752-8222,2021-06-30
2,관광호텔업,제주KAL호텔,제주특별자치도 제주시 중앙로 151,282,064-724-2001,2021-06-30
3,관광호텔업,제주썬호텔,제주특별자치도 제주시 삼무로 67,203,064-741-8000,2021-06-30
4,관광호텔업,제주퍼시픽호텔,제주특별자치도 제주시 서사로 20,177,064-758-2500,2021-06-30

In [19]:
# 컬럼명 변경

part1.rename(columns = {'소재지':'도로명주소', '연락처':'전화번호'},inplace=True)
part1.head()

,구분,상호명,도로명주소,객실수,전화번호,데이터기준일자
0,관광호텔업,글래드호텔앤리조트(주)메종글래드제주,제주특별자치도 제주시 노연로 80,513,064-747-5000,2021-06-30
1,관광호텔업,제주오리엔탈호텔,제주특별자치도 제주시 탑동로 47,321,064-752-8222,2021-06-30
2,관광호텔업,제주KAL호텔,제주특별자치도 제주시 중앙로 151,282,064-724-2001,2021-06-30
3,관광호텔업,제주썬호텔,제주특별자치도 제주시 삼무로 67,203,064-741-8000,2021-06-30
4,관광호텔업,제주퍼시픽호텔,제주특별자치도 제주시 서사로 20,177,064-758-2500,2021-06-30

In [20]:
# '데이터기준일자'. '비고' 제거

part1 = part1.drop(['데이터기준일자'], axis=1)
part1.head()

      구분                  상호명                도로명주소  객실수          전화번호
0  관광호텔업  글래드호텔앤리조트(주)메종글래드제주   제주특별자치도 제주시 노연로 80  513  064-747-5000
1  관광호텔업             제주오리엔탈호텔   제주특별자치도 제주시 탑동로 47  321  064-752-8222
2  관광호텔업              제주KAL호텔  제주특별자치도 제주시 중앙로 151  282  064-724-2001
3  관광호텔업                제주썬호텔   제주특별자치도 제주시 삼무로 67  203  064-741-8000
4  관광호텔업              제주퍼시픽호텔   제주특별자치도 제주시 서사로 20  177  064-758-2500

In [21]:
# 누락 데이터 확인

part1.count()

구분       424
상호명      424
도로명주소    424
객실수      424
전화번호     418
dtype: int64

In [22]:
# 완전히 동일한 중복데이터 여부 확인

part1.duplicated().sum()

0

In [23]:
print(part1.shape)
print(list(part1.columns))
part1.head()

(424, 5)
['구분', '상호명', '도로명주소', '객실수', '전화번호']

      구분                  상호명                도로명주소  객실수          전화번호
0  관광호텔업  글래드호텔앤리조트(주)메종글래드제주   제주특별자치도 제주시 노연로 80  513  064-747-5000
1  관광호텔업             제주오리엔탈호텔   제주특별자치도 제주시 탑동로 47  321  064-752-8222
2  관광호텔업              제주KAL호텔  제주특별자치도 제주시 중앙로 151  282  064-724-2001
3  관광호텔업                제주썬호텔   제주특별자치도 제주시 삼무로 67  203  064-741-8000
4  관광호텔업              제주퍼시픽호텔   제주특별자치도 제주시 서사로 20  177  064-758-2500

In [24]:
# 컬럼별로 중복데이터 여부 확인

part1['상호명'].value_counts()

(주)블랙스톤리조트             2
글래드호텔앤리조트(주)메종글래드제주    1
아이리스호스텔                1
불란지호스텔                 1
제주세인트하우스               1
                      ..
로긴리조트                  1
부띠끄호텔빌라드애월             1
(주)하바나호텔앤리조트           1
제주나인리조트                1
백통신원리조트 기린             1
Name: 상호명, Length: 423, dtype: int64

In [25]:
# 중복 발생
# 한 상호명에 여러 업을 운영할 수도 있다고 판단해서 중복 삭제 안함

part1[part1.상호명 == '(주)블랙스톤리조트']

           구분         상호명                        도로명주소  객실수          전화번호
19      관광호텔업  (주)블랙스톤리조트  제주특별자치도 제주시 한림읍 한창로 925-122   36  064-795-2126
379  휴양콘도미니엄업  (주)블랙스톤리조트  제주특별자치도 제주시 한림읍 한창로 925-122   50  064-795-2126

In [26]:
# 컬럼별로 중복데이터 여부 확인

part1['도로명주소'].value_counts()

제주특별자치도 서귀포시 표선면 일주동로 6347-17    2
제주특별자치도 제주시 한림읍 금능남로 127         2
제주특별자치도 서귀포시 표선면 민속해안로 537       2
제주특별자치도 제주시 조천읍 신북로 577          2
제주특별자치도 제주시 애월읍 애월해안로 400-9      2
                                ..
제주특별자치도 제주시 일주서로 7531            1
제주특별자치도 제주시 도령로 102              1
제주특별자치도 제주시 한림읍 한림로 77           1
제주특별자치도 제주시 서해안로 442-11          1
제주특별자치도 서귀포시 남원읍 서성로 427-1       1
Name: 도로명주소, Length: 415, dtype: int64

In [27]:
# 중복 발생
# 한 도로명주소에 여러 업소가 있을 수 있다고 판단해서 중복 삭제 안함

part1[part1.도로명주소 == '제주특별자치도 제주시 한림읍 금능남로 127']

           구분       상호명                     도로명주소  객실수          전화번호
26      관광호텔업    호텔라온제주  제주특별자치도 제주시 한림읍 금능남로 127   51  064-795-8000
387  휴양콘도미니엄업  라온프라이빗타운  제주특별자치도 제주시 한림읍 금능남로 127  934  064-795-3001

In [28]:
# 컬럼별로 중복데이터 여부 확인

part1['전화번호'].value_counts()

064-784-7337    4
064-792-4723    3
064-799-3544    3
064-805-7600    2
064-792-0045    2
               ..
064-723-3333    1
064-720-9000    1
064-782-1000    1
064-722-2222    1
064-745-7077    1
Name: 전화번호, Length: 393, dtype: int64

In [29]:
# 중복 발생
# 여러 업소의 소재지가 매우 유사해서 동일한 전화번호로 운영하고 있을 수 있다고 판단해서 중복 삭제 안함

part1[part1.전화번호 == '064-799-3544']

,구분,상호명,도로명주소,객실수,전화번호
54,관광호텔업,애월바다호텔 제주,제주특별자치도 제주시 애월읍 애월해안로 554-10,94,064-799-3544
60,관광호텔업,베니키아호텔제주,제주특별자치도 제주시 애월읍 애월해안로 554-6,88,064-799-3544
196,호스텔업,씨클리프호텔제주(구. 윈드힐호텔&리조트),제주특별자치도 제주시 애월읍 애월해안로 554-8,41,064-799-3544

In [30]:
# 중복 발생
# 여러 업소의 소재지가 매우 유사해서 동일한 전화번호로 운영하고 있을 수 있다고 판단해서 중복 삭제 안함

part1[part1.전화번호 == '064-780-8000']

           구분     상호명                       도로명주소  객실수          전화번호
90      관광호텔업   해비치호텔  제주특별자치도 서귀포시 표선면 민속해안로 537  288  064-780-8000
397  휴양콘도미니엄업  해비치리조트  제주특별자치도 서귀포시 표선면 민속해안로 537  215  064-780-8000

In [31]:
# 중복 발생
# 여러 업소의 소재지가 매우 유사해서 동일한 전화번호로 운영하고 있을 수 있다고 판단해서 중복 삭제 안함

part1[part1.전화번호 == '064-784-2211']

        구분          상호명                         도로명주소  객실수          전화번호
172  가족호텔업    봄그리고가을리조트  제주특별자치도 서귀포시 성산읍 해맞이해안로 2660   46  064-784-2211
177  가족호텔업  봄그리고가을 가족호텔  제주특별자치도 서귀포시 성산읍 해맞이해안로 2652   86  064-784-2211

In [32]:
# 중복 발생
# 여러 업소의 소재지가 매우 유사해서 동일한 전화번호로 운영하고 있을 수 있다고 판단해서 중복 삭제 안함

part1[part1.전화번호 == '064-799-1671']

       구분       상호명                  도로명주소  객실수          전화번호
45  관광호텔업     루스톤호텔  제주특별자치도 제주시 애월해안로 408   42  064-799-1671
46  관광호텔업  루스톤빌라앤호텔  제주특별자치도 제주시 애월해안로 406   38  064-799-1671

In [33]:
# 중복 발생
# 여러 업소의 소재지가 매우 유사해서 동일한 전화번호로 운영하고 있을 수 있다고 판단해서 중복 삭제 안함

part1[part1.전화번호 == '064-799-2600']

        구분          상호명                        도로명주소  객실수          전화번호
130  가족호텔업        다인리조트  제주특별자치도 제주시 애월읍 애월해안로 400-9   43  064-799-2600
133  가족호텔업  다인리조트 투(2차)  제주특별자치도 제주시 애월읍 애월해안로 400-9   39  064-799-2600

In [34]:
# 전화번호 결측값 찾기

part1.loc[part1['전화번호'].isna()]

        구분        상호명                       도로명주소  객실수 전화번호
166  가족호텔업     아라온리조트      제주특별자치도 서귀포시 소보리당로 220   55  NaN
252   호스텔업      마음스테이  제주특별자치도 제주시 구좌읍 평대13길 42-1   20  NaN
353   호스텔업  부띠끄스테이 스놉       제주특별자치도 서귀포시 예래해안로 17   20  NaN
355   호스텔업    호텔 서귀피안    제주특별자치도 서귀포시 보목로64번길 178   30  NaN
356   호스텔업         엘르       제주특별자치도 서귀포시 이어도로 152   23  NaN
357   호스텔업  더 그랜드 섬오름       제주특별자치도 서귀포시 막숙포로 118   79  NaN

# Part1 + part2 병합

In [35]:
new_part = pd.concat([part1, part2])

In [36]:
print(new_part.shape)
print(list(new_part.columns))
new_part.head()

(631, 5)
['구분', '상호명', '도로명주소', '객실수', '전화번호']

      구분                  상호명                도로명주소  객실수          전화번호
0  관광호텔업  글래드호텔앤리조트(주)메종글래드제주   제주특별자치도 제주시 노연로 80  513  064-747-5000
1  관광호텔업             제주오리엔탈호텔   제주특별자치도 제주시 탑동로 47  321  064-752-8222
2  관광호텔업              제주KAL호텔  제주특별자치도 제주시 중앙로 151  282  064-724-2001
3  관광호텔업                제주썬호텔   제주특별자치도 제주시 삼무로 67  203  064-741-8000
4  관광호텔업              제주퍼시픽호텔   제주특별자치도 제주시 서사로 20  177  064-758-2500

In [37]:
# 누락 데이터 확인

new_part.count()

구분       631
상호명      631
도로명주소    631
객실수      631
전화번호     624
dtype: int64

In [38]:
# 누락 데이터 확인

new_part.isnull().sum()

구분       0
상호명      0
도로명주소    0
객실수      0
전화번호     7
dtype: int64

In [39]:
# 완전히 동일한 중복데이터 여부 확인

new_part.duplicated().sum()

160

In [40]:
# 연락처 결측값 찾기

new_part.loc[new_part['전화번호'].isna()]

        구분        상호명                       도로명주소  객실수 전화번호
166  가족호텔업     아라온리조트      제주특별자치도 서귀포시 소보리당로 220   55  NaN
252   호스텔업      마음스테이  제주특별자치도 제주시 구좌읍 평대13길 42-1   20  NaN
353   호스텔업  부띠끄스테이 스놉       제주특별자치도 서귀포시 예래해안로 17   20  NaN
355   호스텔업    호텔 서귀피안    제주특별자치도 서귀포시 보목로64번길 178   30  NaN
356   호스텔업         엘르       제주특별자치도 서귀포시 이어도로 152   23  NaN
357   호스텔업  더 그랜드 섬오름       제주특별자치도 서귀포시 막숙포로 118   79  NaN
179   호스텔업      마음스테이  제주특별자치도 제주시 구좌읍 평대13길 42-1   20  NaN

In [41]:
# '데이터기준일자', '비고'를 제외한 중복데이터 여부를 파악하기 위해 진행

new_part.iloc[:,[0,1,2,3,4]]

,구분,상호명,도로명주소,객실수,전화번호
0,관광호텔업,글래드호텔앤리조트(주)메종글래드제주,제주특별자치도 제주시 노연로 80,513,064-747-5000
1,관광호텔업,제주오리엔탈호텔,제주특별자치도 제주시 탑동로 47,321,064-752-8222
2,관광호텔업,제주KAL호텔,제주특별자치도 제주시 중앙로 151,282,064-724-2001
3,관광호텔업,제주썬호텔,제주특별자치도 제주시 삼무로 67,203,064-741-8000
4,관광호텔업,제주퍼시픽호텔,제주특별자치도 제주시 서사로 20,177,064-758-2500
...,...,...,...,...,...
202,휴양콘도미니엄업,아덴힐리조트&골프클럽,제주특별자치도 제주시 한림읍 화전길 82,414,064-730-7023
203,휴양콘도미니엄업,라온프라이빗타운,제주특별자치도 제주시 한림읍 금능남로 127,934,064-795-3001
204,휴양콘도미니엄업,소노벨 타워 C 제주,제주특별자치도 제주시 조천읍 신북로 577,156,064-780-5040
205,휴양콘도미니엄업,㈜케이피씨(구.㈜한국폴로컨트리클럽휴양콘도미니엄),제주특별자치도 제주시 구좌읍 월행남길 322-30,33,064-784-9020
206,휴양콘도미니엄업,캠퍼트리호텔앤리조트,제주특별자치도 제주시 해안마을서4길 100,151,064-795-8888

In [42]:
# '데이터기준일자', '비고'를 제외한 중복데이터 여부를 파악하기 위해 진행

a = new_part.iloc[:,[0,1,2,3,4]]

In [43]:
# 완전히 동일한 중복데이터 여부 확인

new_part.duplicated().sum()

160

In [44]:
# 중복 데이터 개수 파악

new_part[new_part.duplicated()==True]

,구분,상호명,도로명주소,객실수,전화번호
1,관광호텔업,제주오리엔탈호텔,제주특별자치도 제주시 탑동로 47,321,064-752-8222
7,관광호텔업,제주선샤인호텔,제주특별자치도 제주시 조천읍 신북로 481-9,72,064-784-2525
9,관광호텔업,제주서울관광호텔,제주특별자치도 제주시 탑동로 5,108,064-752-2211
10,관광호텔업,제주팔레스관광호텔,제주특별자치도 제주시 탑동로 9,94,064-753-8811
16,관광호텔업,금룡관광호텔,제주특별자치도 제주시 삼무로 79,70,064-747-8885
...,...,...,...,...,...
200,휴양콘도미니엄업,크라운컨트리클럽 골프 빌리지,제주특별자치도 제주시 조천읍 북선로 125,25,064-784-4811
202,휴양콘도미니엄업,아덴힐리조트&골프클럽,제주특별자치도 제주시 한림읍 화전길 82,414,064-730-7023
203,휴양콘도미니엄업,라온프라이빗타운,제주특별자치도 제주시 한림읍 금능남로 127,934,064-795-3001
205,휴양콘도미니엄업,㈜케이피씨(구.㈜한국폴로컨트리클럽휴양콘도미니엄),제주특별자치도 제주시 구좌읍 월행남길 322-30,33,064-784-9020
206,휴양콘도미니엄업,캠퍼트리호텔앤리조트,제주특별자치도 제주시 해안마을서4길 100,151,064-795-8888

In [45]:
# 컬럼 추가

new_part['행정시'] = np.nan
new_part['위도'] = np.nan
new_part['경도'] = np.nan

In [46]:
# 컬럼명 순서변경

new_part= new_part[['상호명', '구분', '행정시', '도로명주소', '전화번호', '위도', 
                   '경도', '객실수']]
new_part.head()

,상호명,구분,행정시,도로명주소,전화번호,위도,경도,객실수
0,글래드호텔앤리조트(주)메종글래드제주,관광호텔업,NaN,제주특별자치도 제주시 노연로 80,064-747-5000,NaN,NaN,513
1,제주오리엔탈호텔,관광호텔업,NaN,제주특별자치도 제주시 탑동로 47,064-752-8222,NaN,NaN,321
2,제주KAL호텔,관광호텔업,NaN,제주특별자치도 제주시 중앙로 151,064-724-2001,NaN,NaN,282
3,제주썬호텔,관광호텔업,NaN,제주특별자치도 제주시 삼무로 67,064-741-8000,NaN,NaN,203
4,제주퍼시픽호텔,관광호텔업,NaN,제주특별자치도 제주시 서사로 20,064-758-2500,NaN,NaN,177

In [47]:
# csv 파일 저장

new_part.to_csv('제주특별자치도_관광숙박업현황_병합.csv', encoding='cp949')