In [1]:
# google drive 마운트
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
import pandas as pd
import numpy as np
  
part1 = pd.read_csv('/content/drive/MyDrive/국민대학원/졸업프로젝트/데이터/1순위/음식/대규모점포정보.csv', encoding='cp949')

# part1 = 대규모점포정보

In [3]:
# part1 = 대규모점포정보

print(part1.shape)
print(list(part1.columns))
part1.head()

(61, 17)
['사업장명', '업종구분대분류', '업종구분소분류', '인허가일자', '인허가취소일자', '영업상태명', '폐업일자', '휴업시작일자', '휴업종료일자', '재개업일자', '소재지면적', '지번주소', '도로명주소', '도로명우편번호', '데이터갱신일자', '위도', '경도']

,사업장명,업종구분대분류,업종구분소분류,인허가일자,인허가취소일자,영업상태명,폐업일자,휴업시작일자,휴업종료일자,재개업일자,소재지면적,지번주소,도로명주소,도로명우편번호,데이터갱신일자,위도,경도
0,한림민속오일시장,대규모점포,시장,20020924,NaN,영업/정상,NaN,NaN,NaN,NaN,2900.0,제주특별자치도 제주시 한림읍 대림리 1698번지 4호,제주특별자치도 제주시 한림읍 한수풀로4길 10,NaN,2018-08-31 23:59:59,33.419832,126.274504
1,세화민속오일시장,대규모점포,시장,19650115,NaN,영업/정상,NaN,NaN,NaN,NaN,3183.0,제주특별자치도 제주시 구좌읍 세화리 1500번지 5호,제주특별자치도 제주시 구좌읍 해맞이해안로 1412,NaN,2018-08-31 23:59:59,33.526186,126.857297
2,함덕오일시장,대규모점포,시장,20071209,NaN,영업/정상,NaN,NaN,NaN,NaN,561.0,제주특별자치도 제주시 조천읍 함덕리 972번지 7호,NaN,NaN,2018-08-31 23:59:59,33.540253,126.667961
3,(주)이마트 신제주점,대규모점포,대형마트,20110531,NaN,영업/정상,NaN,NaN,NaN,NaN,7148.4,NaN,제주특별자치도 제주시 1100로 3348 (노형동),690802.0,2020-04-23 02:40:00,33.484965,126.480432
4,뉴월드마트,대규모점포,대형마트,19961022,NaN,영업/정상,NaN,NaN,NaN,NaN,NaN,제주특별자치도 제주시 연동 303번지 17 호,NaN,NaN,2018-08-31 23:59:59,33.486961,126.497115

In [4]:
# 컬럼 삭제

part1 = part1.drop(['업종구분대분류', '인허가일자', '인허가취소일자', '폐업일자', 
                    '휴업시작일자', '휴업종료일자', '재개업일자', '소재지면적', '지번주소', '도로명우편번호', '데이터갱신일자'], axis=1)
part1.head()

,사업장명,업종구분소분류,영업상태명,도로명주소,위도,경도
0,한림민속오일시장,시장,영업/정상,제주특별자치도 제주시 한림읍 한수풀로4길 10,33.419832,126.274504
1,세화민속오일시장,시장,영업/정상,제주특별자치도 제주시 구좌읍 해맞이해안로 1412,33.526186,126.857297
2,함덕오일시장,시장,영업/정상,NaN,33.540253,126.667961
3,(주)이마트 신제주점,대형마트,영업/정상,제주특별자치도 제주시 1100로 3348 (노형동),33.484965,126.480432
4,뉴월드마트,대형마트,영업/정상,NaN,33.486961,126.497115

In [5]:
# 컬럼명 변경

part1.rename(columns = {'사업장명':'업소명', '업종구분소분류':'업종'},inplace=True)
part1.head()

,업소명,업종,영업상태명,도로명주소,위도,경도
0,한림민속오일시장,시장,영업/정상,제주특별자치도 제주시 한림읍 한수풀로4길 10,33.419832,126.274504
1,세화민속오일시장,시장,영업/정상,제주특별자치도 제주시 구좌읍 해맞이해안로 1412,33.526186,126.857297
2,함덕오일시장,시장,영업/정상,NaN,33.540253,126.667961
3,(주)이마트 신제주점,대형마트,영업/정상,제주특별자치도 제주시 1100로 3348 (노형동),33.484965,126.480432
4,뉴월드마트,대형마트,영업/정상,NaN,33.486961,126.497115

In [6]:
# 컬럼별로 중복데이터 여부 확인

part1['영업상태명'].value_counts()

영업/정상             45
휴업                 7
폐업                 6
취소/말소/만료/정지/중지     3
Name: 영업상태명, dtype: int64

In [7]:
# '영업상태명' 컬럼에 있는 '폐업'이 들어가 행을 삭제

part1 = part1[part1.영업상태명 != '폐업']
part1.head()

,업소명,업종,영업상태명,도로명주소,위도,경도
0,한림민속오일시장,시장,영업/정상,제주특별자치도 제주시 한림읍 한수풀로4길 10,33.419832,126.274504
1,세화민속오일시장,시장,영업/정상,제주특별자치도 제주시 구좌읍 해맞이해안로 1412,33.526186,126.857297
2,함덕오일시장,시장,영업/정상,NaN,33.540253,126.667961
3,(주)이마트 신제주점,대형마트,영업/정상,제주특별자치도 제주시 1100로 3348 (노형동),33.484965,126.480432
4,뉴월드마트,대형마트,영업/정상,NaN,33.486961,126.497115

In [8]:
# '영업상태명' 컬럼에 있는 '폐업'이 들어가 행을 삭제

part1 = part1[part1.영업상태명 != '취소/말소/만료/정지/중지']
part1.head()

,업소명,업종,영업상태명,도로명주소,위도,경도
0,한림민속오일시장,시장,영업/정상,제주특별자치도 제주시 한림읍 한수풀로4길 10,33.419832,126.274504
1,세화민속오일시장,시장,영업/정상,제주특별자치도 제주시 구좌읍 해맞이해안로 1412,33.526186,126.857297
2,함덕오일시장,시장,영업/정상,NaN,33.540253,126.667961
3,(주)이마트 신제주점,대형마트,영업/정상,제주특별자치도 제주시 1100로 3348 (노형동),33.484965,126.480432
4,뉴월드마트,대형마트,영업/정상,NaN,33.486961,126.497115

In [9]:
# 컬럼별로 중복데이터 여부 확인

part1['영업상태명'].value_counts()

영업/정상    45
휴업        7
Name: 영업상태명, dtype: int64

In [10]:
# 컬럼 삭제

part1 = part1.drop(['영업상태명'], axis=1)
part1.head()

           업소명    업종                         도로명주소         위도          경도
0     한림민속오일시장    시장     제주특별자치도 제주시 한림읍 한수풀로4길 10  33.419832  126.274504
1     세화민속오일시장    시장   제주특별자치도 제주시 구좌읍 해맞이해안로 1412  33.526186  126.857297
2       함덕오일시장    시장                           NaN  33.540253  126.667961
3  (주)이마트 신제주점  대형마트  제주특별자치도 제주시 1100로 3348 (노형동)  33.484965  126.480432
4        뉴월드마트  대형마트                           NaN  33.486961  126.497115

In [11]:
# 컬럼 추가

part1['행정시'] = np.nan
part1['업태'] = np.nan
part1['전화번호'] = np.nan
part1.head()

,업소명,업종,도로명주소,위도,경도,행정시,업태,전화번호
0,한림민속오일시장,시장,제주특별자치도 제주시 한림읍 한수풀로4길 10,33.419832,126.274504,NaN,NaN,NaN
1,세화민속오일시장,시장,제주특별자치도 제주시 구좌읍 해맞이해안로 1412,33.526186,126.857297,NaN,NaN,NaN
2,함덕오일시장,시장,NaN,33.540253,126.667961,NaN,NaN,NaN
3,(주)이마트 신제주점,대형마트,제주특별자치도 제주시 1100로 3348 (노형동),33.484965,126.480432,NaN,NaN,NaN
4,뉴월드마트,대형마트,NaN,33.486961,126.497115,NaN,NaN,NaN

In [12]:
# 컬럼명 순서변경

part1 = part1[['업소명', '업종', '업태', '행정시', '도로명주소', '전화번호', '위도', '경도']]
part1.head()

,업소명,업종,업태,행정시,도로명주소,전화번호,위도,경도
0,한림민속오일시장,시장,NaN,NaN,제주특별자치도 제주시 한림읍 한수풀로4길 10,NaN,33.419832,126.274504
1,세화민속오일시장,시장,NaN,NaN,제주특별자치도 제주시 구좌읍 해맞이해안로 1412,NaN,33.526186,126.857297
2,함덕오일시장,시장,NaN,NaN,NaN,NaN,33.540253,126.667961
3,(주)이마트 신제주점,대형마트,NaN,NaN,제주특별자치도 제주시 1100로 3348 (노형동),NaN,33.484965,126.480432
4,뉴월드마트,대형마트,NaN,NaN,NaN,NaN,33.486961,126.497115

In [13]:
# 누락 데이터 확인

part1.count()

업소명      52
업종       52
업태        0
행정시       0
도로명주소    37
전화번호      0
위도       42
경도       42
dtype: int64

In [14]:
# 누락 데이터 확인

part1.isnull().sum()

업소명       0
업종        0
업태       52
행정시      52
도로명주소    15
전화번호     52
위도       10
경도       10
dtype: int64

In [15]:
# part1 = 대규모점포정보

print(part1.shape)
print(list(part1.columns))
part1.head()

(52, 8)
['업소명', '업종', '업태', '행정시', '도로명주소', '전화번호', '위도', '경도']

,업소명,업종,업태,행정시,도로명주소,전화번호,위도,경도
0,한림민속오일시장,시장,NaN,NaN,제주특별자치도 제주시 한림읍 한수풀로4길 10,NaN,33.419832,126.274504
1,세화민속오일시장,시장,NaN,NaN,제주특별자치도 제주시 구좌읍 해맞이해안로 1412,NaN,33.526186,126.857297
2,함덕오일시장,시장,NaN,NaN,NaN,NaN,33.540253,126.667961
3,(주)이마트 신제주점,대형마트,NaN,NaN,제주특별자치도 제주시 1100로 3348 (노형동),NaN,33.484965,126.480432
4,뉴월드마트,대형마트,NaN,NaN,NaN,NaN,33.486961,126.497115

In [16]:
# csv 파일 저장

part1.to_csv('제주특별자치도_대규모점포.csv', encoding='cp949')